use crate::manifest;
use anyhow::{anyhow, bail, Context, Result};
use serde_json::{json, Map, Value};
use std::path::{Path, PathBuf};
use std::process::Command;

const PI_EXTENSION: &str = r#"/**
 * agentws project extension
 *
 * Native repo discovery/request tools plus a soft scope guard for path-based
 * file tools. Generated by `agentws integrate pi`.
 */
import { Type } from "@earendil-works/pi-ai";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { dirname, isAbsolute, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const workspaceRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

export default function (pi: ExtensionAPI) {
  async function callAgentws(
    name: string,
    args: Record<string, unknown>,
    signal: AbortSignal | undefined,
    cwd: string,
  ) {
    const binary = process.env.AGENTWS_BIN || "agentws";
    const result = await pi.exec(binary, ["_tool-call", name, JSON.stringify(args)], {
      cwd,
      signal,
    });
    if (result.code !== 0) {
      throw new Error((result.stderr || result.stdout || `agentws exited ${result.code}`).trim());
    }
    return result.stdout.trim();
  }

  pi.registerTool({
    name: "list_available_repos",
    label: "Available Repositories",
    description: "List repositories that can be requested for this agentws workspace.",
    promptSnippet: "List repositories available outside the current agentws scope",
    parameters: Type.Object({
      query: Type.Optional(Type.String({ description: "Optional fuzzy name filter" })),
    }),
    async execute(_id, params, signal, _update, ctx) {
      const text = await callAgentws("list_available_repos", params, signal, ctx.cwd);
      return { content: [{ type: "text", text }], details: { query: params.query } };
    },
  });

  pi.registerTool({
    name: "request_repo",
    label: "Request Repository",
    description: "Request human approval to add a repository to this live workspace.",
    promptSnippet: "Request human-approved access to another repository",
    promptGuidelines: [
      "Use request_repo instead of reading or cloning repositories outside the agentws workspace.",
    ],
    parameters: Type.Object({
      name: Type.String({ description: "Repository name" }),
      reason: Type.Optional(Type.String({ description: "Why this task needs the repository" })),
    }),
    async execute(_id, params, signal, _update, ctx) {
      const text = await callAgentws("request_repo", params, signal, ctx.cwd);
      ctx.ui.notify(text, "info");
      return { content: [{ type: "text", text }], details: { request: params } };
    },
  });

  pi.registerTool({
    name: "check_request",
    label: "Check Repository Request",
    description: "Check whether a repository request was approved or denied.",
    promptSnippet: "Check a pending agentws repository request",
    parameters: Type.Object({
      id: Type.String({ description: "Request id returned by request_repo" }),
    }),
    async execute(_id, params, signal, _update, ctx) {
      const text = await callAgentws("check_request", params, signal, ctx.cwd);
      return { content: [{ type: "text", text }], details: { id: params.id } };
    },
  });

  pi.registerTool({
    name: "delete_workspaces",
    label: "Delete Workspaces",
    description: "Preview or delete named agentws workspaces. Preview is the default.",
    promptSnippet: "Preview or delete named agentws workspaces",
    promptGuidelines: [
      "Call with dry_run=true first. Set dry_run=false and confirmed=true only when the user explicitly requested deletion.",
    ],
    parameters: Type.Object({
      stories: Type.Array(Type.String({ description: "Exact workspace name" }), { minItems: 1 }),
      dry_run: Type.Optional(Type.Boolean({ default: true })),
      force: Type.Optional(Type.Boolean({ default: false })),
      confirmed: Type.Optional(Type.Boolean({ default: false })),
    }),
    async execute(_id, params, signal, _update, ctx) {
      const text = await callAgentws("delete_workspaces", params, signal, ctx.cwd);
      ctx.ui.notify(text, "info");
      return { content: [{ type: "text", text }], details: { deletion: params } };
    },
  });

  const pathTools = new Set(["read", "write", "edit", "grep", "find", "ls"]);
  pi.on("tool_call", async (event, ctx) => {
    if (!pathTools.has(event.toolName)) return undefined;
    const rawPath = (event.input as { path?: unknown }).path;
    if (typeof rawPath !== "string" || rawPath.length === 0) return undefined;

    const target = resolve(ctx.cwd, rawPath.replace(/^@/, ""));
    const fromRoot = relative(workspaceRoot, target);
    const outside = fromRoot === ".." || fromRoot.startsWith(`..${sep}`) || isAbsolute(fromRoot);
    if (!outside) return undefined;

    if (!ctx.hasUI) {
      return { block: true, reason: `Path is outside the agentws workspace: ${rawPath}` };
    }
    const choice = await ctx.ui.select(
      `Path is outside the agentws workspace:\n\n  ${rawPath}\n\nAllow this tool call?`,
      ["Allow once", "Block"],
    );
    if (choice !== "Allow once") {
      return { block: true, reason: `Out-of-workspace path blocked: ${rawPath}` };
    }
    return undefined;
  });
}
"#;

pub fn install(story: Option<String>, agents: Vec<String>, force: bool) -> Result<()> {
    if agents.is_empty() {
        bail!("choose at least one integration: pi, claude, codex, opencode, or all");
    }
    let story = manifest::resolve_story(story)?;
    let ws = manifest::load(&story)?;
    let agentws = std::env::current_exe().context("locating the agentws executable")?;
    let expanded = expand_agents(&agents)?;

    for agent in expanded {
        match agent.as_str() {
            "pi" => install_pi(&ws.root, force)?,
            "claude" => install_claude(&ws.root, &agentws, force)?,
            "opencode" => install_opencode(&ws.root, &agentws, force)?,
            "codex" => install_codex(&agentws, force)?,
            _ => unreachable!(),
        }
        println!("integrated agentws with {agent} for workspace '{story}'.");
    }
    Ok(())
}

fn expand_agents(agents: &[String]) -> Result<Vec<String>> {
    let mut out = Vec::new();
    for raw in agents {
        let agent = raw.to_ascii_lowercase();
        let names: &[&str] = match agent.as_str() {
            "all" => &["pi", "claude", "codex", "opencode"],
            "pi" => &["pi"],
            "claude" | "claude-code" => &["claude"],
            "codex" => &["codex"],
            "opencode" => &["opencode"],
            _ => bail!("unknown agent '{raw}' (expected: pi, claude, codex, opencode, or all)"),
        };
        for name in names {
            if !out.iter().any(|existing| existing == name) {
                out.push((*name).to_string());
            }
        }
    }
    Ok(out)
}

fn install_pi(root: &Path, force: bool) -> Result<()> {
    let path = root.join(".pi/extensions/agentws.ts");
    write_managed_file(&path, PI_EXTENSION.as_bytes(), force)
}

fn install_claude(root: &Path, agentws: &Path, force: bool) -> Result<()> {
    let entry = json!({
        "command": agentws.to_string_lossy(),
        "args": ["mcp"]
    });
    merge_json_integration(&root.join(".mcp.json"), "mcpServers", entry, force)
}

fn install_opencode(root: &Path, agentws: &Path, force: bool) -> Result<()> {
    let entry = json!({
        "type": "local",
        "command": [agentws.to_string_lossy(), "mcp"],
        "enabled": true
    });
    merge_json_integration(&root.join("opencode.json"), "mcp", entry, force)
}

fn merge_json_integration(path: &Path, section: &str, entry: Value, force: bool) -> Result<()> {
    let mut document = if path.exists() {
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("reading integration config {}", path.display()))?;
        serde_json::from_str::<Value>(&text)
            .with_context(|| format!("parsing integration config {}", path.display()))?
    } else {
        Value::Object(Map::new())
    };
    let root = document.as_object_mut().ok_or_else(|| {
        anyhow!(
            "integration config {} must contain a JSON object",
            path.display()
        )
    })?;
    let section_value = root
        .entry(section.to_string())
        .or_insert_with(|| Value::Object(Map::new()));
    let section_object = section_value.as_object_mut().ok_or_else(|| {
        anyhow!(
            "'{section}' in integration config {} must be an object",
            path.display()
        )
    })?;
    if let Some(existing) = section_object.get("agentws") {
        if existing == &entry {
            return Ok(());
        }
        if !force {
            bail!(
                "{} already has a different '{section}.agentws' entry; inspect it or pass --force",
                path.display()
            );
        }
    }
    section_object.insert("agentws".into(), entry);
    let mut encoded = serde_json::to_vec_pretty(&document)?;
    encoded.push(b'\n');
    write_atomic(path, &encoded)
}

fn install_codex(agentws: &Path, force: bool) -> Result<()> {
    let codex =
        find_on_path("codex").ok_or_else(|| anyhow!("codex is not installed or on PATH"))?;
    let existing = Command::new(&codex)
        .args(["mcp", "get", "agentws"])
        .output()
        .context("checking the Codex MCP configuration")?;
    if existing.status.success() {
        let description = String::from_utf8_lossy(&existing.stdout);
        let expected = agentws.to_string_lossy();
        if description.contains(expected.as_ref()) && description.contains("mcp") {
            return Ok(());
        }
        if !force {
            bail!(
                "Codex already has a different MCP server named 'agentws'; inspect it with \
                 `codex mcp get agentws` or pass --force"
            );
        }
        let removed = Command::new(&codex)
            .args(["mcp", "remove", "agentws"])
            .status()
            .context("removing the old Codex agentws MCP entry")?;
        if !removed.success() {
            bail!("Codex could not remove the old agentws MCP entry");
        }
    }

    let added = Command::new(&codex)
        .args(["mcp", "add", "agentws", "--"])
        .arg(agentws)
        .arg("mcp")
        .status()
        .context("adding the agentws MCP server to Codex")?;
    if !added.success() {
        bail!("`codex mcp add` failed");
    }
    Ok(())
}

fn write_managed_file(path: &Path, content: &[u8], force: bool) -> Result<()> {
    if let Ok(existing) = std::fs::read(path) {
        if existing == content {
            return Ok(());
        }
        if !force {
            bail!(
                "{} already exists with different content; inspect it or pass --force",
                path.display()
            );
        }
    }
    write_atomic(path, content)
}

fn write_atomic(path: &Path, content: &[u8]) -> Result<()> {
    let parent = path
        .parent()
        .ok_or_else(|| anyhow!("path {} has no parent", path.display()))?;
    std::fs::create_dir_all(parent)?;
    let temp = path.with_extension(format!("agentws-{}.tmp", crate::ops::new_id()));
    std::fs::write(&temp, content)
        .with_context(|| format!("writing temporary integration file {}", temp.display()))?;
    std::fs::rename(&temp, path)
        .with_context(|| format!("updating integration file {}", path.display()))?;
    Ok(())
}

fn find_on_path(name: &str) -> Option<PathBuf> {
    std::env::var_os("PATH").and_then(|path| {
        std::env::split_paths(&path)
            .map(|dir| dir.join(name))
            .find(|candidate| candidate.is_file())
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn expands_all_agents_once() {
        let agents = expand_agents(&["pi".into(), "all".into()]).unwrap();
        assert_eq!(agents, ["pi", "claude", "codex", "opencode"]);
    }

    #[test]
    fn project_json_merge_preserves_unrelated_settings() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("opencode.json");
        std::fs::write(
            &path,
            r#"{"theme":"dark","mcp":{"other":{"type":"remote"}}}"#,
        )
        .unwrap();
        let entry = json!({ "type": "local", "command": ["agentws", "mcp"] });
        merge_json_integration(&path, "mcp", entry.clone(), false).unwrap();

        let saved: Value = serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
        assert_eq!(saved["theme"], "dark");
        assert_eq!(saved["mcp"]["other"]["type"], "remote");
        assert_eq!(saved["mcp"]["agentws"], entry);
    }

    #[test]
    fn project_json_merge_requires_force_for_conflict() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join(".mcp.json");
        std::fs::write(&path, r#"{"mcpServers":{"agentws":{"command":"other"}}}"#).unwrap();
        let entry = json!({ "command": "agentws", "args": ["mcp"] });
        assert!(merge_json_integration(&path, "mcpServers", entry.clone(), false).is_err());
        merge_json_integration(&path, "mcpServers", entry.clone(), true).unwrap();
        let saved: Value = serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
        assert_eq!(saved["mcpServers"]["agentws"], entry);
    }

    #[test]
    fn pi_extension_contains_native_tools_and_scope_guard() {
        for needle in [
            "list_available_repos",
            "request_repo",
            "check_request",
            "delete_workspaces",
            "tool_call",
            "outside the agentws workspace",
        ] {
            assert!(PI_EXTENSION.contains(needle));
        }
    }

    #[test]
    fn pi_can_load_generated_extension_when_installed() {
        let Some(pi) = find_on_path("pi") else {
            eprintln!("pi is not installed; skipping extension load test");
            return;
        };
        let tmp = tempfile::tempdir().unwrap();
        let extension = tmp.path().join(".pi/extensions/agentws.ts");
        write_managed_file(&extension, PI_EXTENSION.as_bytes(), false).unwrap();
        let output = Command::new(pi)
            .args([
                "--offline",
                "--extension",
                extension.to_str().unwrap(),
                "--list-models",
            ])
            .env("PI_CODING_AGENT_DIR", tmp.path().join("pi-agent"))
            .current_dir(tmp.path())
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "pi could not load generated extension ({}):\nstdout:\n{}\nstderr:\n{}",
            output.status,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
